server:
  port: 8082

custom:
  greeting: "Hola desde config server me"

spring:
  config:
    import: "optional:configserver: "

service:
  ms-products-dbrestaurant:
    url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: "always"

